export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const HTTP_GET_EMPLOYEES = "HTTP_GET_EMPLOYEES";
export const HTTP_POST_EMPLOYEE = "HTTP_POST_EMPLOYEE";
export const HTTP_DELETE_EMPLOYEE = "HTTP_DELETE_EMPLOYEE";
export const HTTP_UPDATE_EMPLOYEE = "HTTP_UPDATE_EMPLOYEE";

